# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QAbstractSpinBox, QApplication, QCheckBox,
    QDockWidget, QFormLayout, QFrame, QGraphicsView,
    QGridLayout, QHBoxLayout, QHeaderView, QLabel,
    QLayout, QMainWindow, QMenu, QMenuBar,
    QScrollArea, QSizePolicy, QSlider, QSpinBox,
    QStatusBar, QTabWidget, QToolBar, QToolButton,
    QTreeWidget, QTreeWidgetItem, QVBoxLayout, QWidget)
import svgicons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(934, 781)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        icon = QIcon()
        icon.addFile(u":/programicon/svgicons/hcie.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentNew))
        self.actionNew.setIcon(icon1)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.actionOpen.setIcon(icon2)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.actionSave.setIcon(icon3)
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentPrint))
        self.actionPrint.setIcon(icon4)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditCut))
        self.actionCut.setIcon(icon5)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon6 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditCopy))
        self.actionCopy.setIcon(icon6)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon7 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditPaste))
        self.actionPaste.setIcon(icon7)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon8 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditUndo))
        self.actionUndo.setIcon(icon8)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon9 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditRedo))
        self.actionRedo.setIcon(icon9)
        self.actionPen = QAction(MainWindow)
        self.actionPen.setObjectName(u"actionPen")
        icon10 = QIcon()
        icon10.addFile(u":/toolbar/svgicons/pen.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPen.setIcon(icon10)
        self.actionLine = QAction(MainWindow)
        self.actionLine.setObjectName(u"actionLine")
        icon11 = QIcon()
        icon11.addFile(u":/toolbar/svgicons/line-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLine.setIcon(icon11)
        self.actionRectangle = QAction(MainWindow)
        self.actionRectangle.setObjectName(u"actionRectangle")
        self.actionEllipse = QAction(MainWindow)
        self.actionEllipse.setObjectName(u"actionEllipse")
        self.actionSpray = QAction(MainWindow)
        self.actionSpray.setObjectName(u"actionSpray")
        self.actionFill = QAction(MainWindow)
        self.actionFill.setObjectName(u"actionFill")
        self.actionTest = QAction(MainWindow)
        self.actionTest.setObjectName(u"actionTest")
        icon12 = QIcon(QIcon.fromTheme(u"accessories-calculator"))
        self.actionTest.setIcon(icon12)
        self.actionTest.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.verticalLayout_4 = QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.scrollArea = QScrollArea(self.tab)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 528, 507))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy1)
        self.gridLayout_2 = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.widgetPicture1 = QFrame(self.scrollAreaWidgetContents)
        self.widgetPicture1.setObjectName(u"widgetPicture1")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.widgetPicture1.sizePolicy().hasHeightForWidth())
        self.widgetPicture1.setSizePolicy(sizePolicy2)
        self.widgetPicture1.setMinimumSize(QSize(100, 100))
        self.widgetPicture1.setMaximumSize(QSize(16777215, 16777215))
        self.widgetPicture1.setMouseTracking(True)
        self.widgetPicture1.setTabletTracking(True)
        self.widgetPicture1.setAutoFillBackground(False)
        self.widgetPicture1.setStyleSheet(u"background-image: url(:/checker/checker20.png);")

        self.gridLayout_2.addWidget(self.widgetPicture1, 0, 0, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_4.addWidget(self.scrollArea)

        self.tabWidget.addTab(self.tab, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 934, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuImage = QMenu(self.menubar)
        self.menuImage.setObjectName(u"menuImage")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuFilters = QMenu(self.menubar)
        self.menuFilters.setObjectName(u"menuFilters")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setMinimumSize(QSize(50, 50))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMaximumSize(QSize(16777215, 500))
        self.toolBar.setMouseTracking(True)
        self.toolBar.setTabletTracking(True)
        self.toolBar.setStyleSheet(u"border-color: rgb(255, 0, 255);")
        self.toolBar.setAllowedAreas(Qt.ToolBarArea.AllToolBarAreas)
        self.toolBar.setIconSize(QSize(16, 16))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.dwTools = QDockWidget(MainWindow)
        self.dwTools.setObjectName(u"dwTools")
        sizePolicy.setHeightForWidth(self.dwTools.sizePolicy().hasHeightForWidth())
        self.dwTools.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayoutWidget = QWidget(self.dockWidgetContents)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 20, 2462, 452))
        self.formLayout = QFormLayout(self.gridLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.formLayout.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setFormAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.toolButtonBrush = QToolButton(self.gridLayoutWidget)
        self.toolButtonBrush.setObjectName(u"toolButtonBrush")
        icon13 = QIcon()
        icon13.addFile(u":/toolbar/svgicons/brush.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonBrush.setIcon(icon13)
        self.toolButtonBrush.setIconSize(QSize(24, 24))
        self.toolButtonBrush.setCheckable(False)
        self.toolButtonBrush.setChecked(False)

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.toolButtonBrush)

        self.toolButtonFill = QToolButton(self.gridLayoutWidget)
        self.toolButtonFill.setObjectName(u"toolButtonFill")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.toolButtonFill.sizePolicy().hasHeightForWidth())
        self.toolButtonFill.setSizePolicy(sizePolicy3)
        icon14 = QIcon()
        icon14.addFile(u":/toolbar/svgicons/Fill.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonFill.setIcon(icon14)
        self.toolButtonFill.setIconSize(QSize(24, 24))
        self.toolButtonFill.setCheckable(False)
        self.toolButtonFill.setChecked(False)

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.toolButtonFill)

        self.toolButtonLine = QToolButton(self.gridLayoutWidget)
        self.toolButtonLine.setObjectName(u"toolButtonLine")
        self.toolButtonLine.setMouseTracking(True)
        self.toolButtonLine.setTabletTracking(True)
        icon15 = QIcon()
        icon15.addFile(u":/toolbar/svgicons/line.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonLine.setIcon(icon15)
        self.toolButtonLine.setIconSize(QSize(24, 24))
        self.toolButtonLine.setCheckable(False)
        self.toolButtonLine.setChecked(False)

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.toolButtonLine)

        self.toolButtonRect = QToolButton(self.gridLayoutWidget)
        self.toolButtonRect.setObjectName(u"toolButtonRect")
        icon16 = QIcon()
        icon16.addFile(u":/toolbar/svgicons/rectangle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonRect.setIcon(icon16)
        self.toolButtonRect.setIconSize(QSize(24, 24))
        self.toolButtonRect.setCheckable(False)
        self.toolButtonRect.setChecked(False)

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.toolButtonRect)

        self.toolButtonCircle = QToolButton(self.gridLayoutWidget)
        self.toolButtonCircle.setObjectName(u"toolButtonCircle")
        icon17 = QIcon()
        icon17.addFile(u":/toolbar/svgicons/circle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonCircle.setIcon(icon17)
        self.toolButtonCircle.setIconSize(QSize(24, 24))
        self.toolButtonCircle.setCheckable(False)
        self.toolButtonCircle.setChecked(False)

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.toolButtonCircle)

        self.toolButtonPen = QToolButton(self.gridLayoutWidget)
        self.toolButtonPen.setObjectName(u"toolButtonPen")
        self.toolButtonPen.setIcon(icon10)
        self.toolButtonPen.setIconSize(QSize(24, 24))
        self.toolButtonPen.setCheckable(False)
        self.toolButtonPen.setChecked(False)

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.toolButtonPen)

        self.toolButtonSelectRectangle = QToolButton(self.gridLayoutWidget)
        self.toolButtonSelectRectangle.setObjectName(u"toolButtonSelectRectangle")
        icon18 = QIcon()
        icon18.addFile(u":/toolbar/svgicons/select-rectangle-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonSelectRectangle.setIcon(icon18)
        self.toolButtonSelectRectangle.setIconSize(QSize(24, 24))

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.toolButtonSelectRectangle)

        self.toolButtonSelectCircle = QToolButton(self.gridLayoutWidget)
        self.toolButtonSelectCircle.setObjectName(u"toolButtonSelectCircle")
        icon19 = QIcon()
        icon19.addFile(u":/toolbar/svgicons/select-circle-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonSelectCircle.setIcon(icon19)
        self.toolButtonSelectCircle.setIconSize(QSize(24, 24))

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.toolButtonSelectCircle)

        self.toolButtonWand = QToolButton(self.gridLayoutWidget)
        self.toolButtonWand.setObjectName(u"toolButtonWand")
        icon20 = QIcon()
        icon20.addFile(u":/toolbar/svgicons/magic.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonWand.setIcon(icon20)
        self.toolButtonWand.setIconSize(QSize(24, 24))

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.toolButtonWand)

        self.toolButtonRoundRect = QToolButton(self.gridLayoutWidget)
        self.toolButtonRoundRect.setObjectName(u"toolButtonRoundRect")
        icon21 = QIcon()
        icon21.addFile(u":/toolbar/svgicons/rounded-rectangle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonRoundRect.setIcon(icon21)
        self.toolButtonRoundRect.setIconSize(QSize(24, 24))

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.toolButtonRoundRect)

        self.toolButtonSpray = QToolButton(self.gridLayoutWidget)
        self.toolButtonSpray.setObjectName(u"toolButtonSpray")
        icon22 = QIcon()
        icon22.addFile(u":/toolbar/svgicons/spray-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonSpray.setIcon(icon22)
        self.toolButtonSpray.setIconSize(QSize(24, 24))
        self.toolButtonSpray.setCheckable(False)
        self.toolButtonSpray.setChecked(False)

        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.toolButtonSpray)

        self.toolButtonEraser = QToolButton(self.gridLayoutWidget)
        self.toolButtonEraser.setObjectName(u"toolButtonEraser")
        icon23 = QIcon()
        icon23.addFile(u":/toolbar/svgicons/eraser-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonEraser.setIcon(icon23)
        self.toolButtonEraser.setIconSize(QSize(24, 24))

        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.toolButtonEraser)

        self.toolButtonText = QToolButton(self.gridLayoutWidget)
        self.toolButtonText.setObjectName(u"toolButtonText")
        icon24 = QIcon()
        icon24.addFile(u":/toolbar/svgicons/text.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonText.setIcon(icon24)
        self.toolButtonText.setIconSize(QSize(24, 24))

        self.formLayout.setWidget(6, QFormLayout.FieldRole, self.toolButtonText)

        self.toolButtonDropper = QToolButton(self.gridLayoutWidget)
        self.toolButtonDropper.setObjectName(u"toolButtonDropper")
        self.toolButtonDropper.setMouseTracking(True)
        self.toolButtonDropper.setTabletTracking(True)
        icon25 = QIcon()
        icon25.addFile(u":/toolbar/svgicons/eyedropper.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonDropper.setIcon(icon25)
        self.toolButtonDropper.setIconSize(QSize(24, 24))
        self.toolButtonDropper.setCheckable(True)
        self.toolButtonDropper.setChecked(False)

        self.formLayout.setWidget(6, QFormLayout.LabelRole, self.toolButtonDropper)

        self.toolButtonZoomIn = QToolButton(self.gridLayoutWidget)
        self.toolButtonZoomIn.setObjectName(u"toolButtonZoomIn")
        icon26 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomIn))
        self.toolButtonZoomIn.setIcon(icon26)
        self.toolButtonZoomIn.setIconSize(QSize(24, 24))
        self.toolButtonZoomIn.setCheckable(False)
        self.toolButtonZoomIn.setChecked(False)

        self.formLayout.setWidget(7, QFormLayout.FieldRole, self.toolButtonZoomIn)

        self.toolButtonZoomReset = QToolButton(self.gridLayoutWidget)
        self.toolButtonZoomReset.setObjectName(u"toolButtonZoomReset")
        icon27 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomFitBest))
        self.toolButtonZoomReset.setIcon(icon27)
        self.toolButtonZoomReset.setIconSize(QSize(24, 24))
        self.toolButtonZoomReset.setCheckable(False)
        self.toolButtonZoomReset.setChecked(False)

        self.formLayout.setWidget(8, QFormLayout.FieldRole, self.toolButtonZoomReset)

        self.toolButtonFlipHorizontal = QToolButton(self.gridLayoutWidget)
        self.toolButtonFlipHorizontal.setObjectName(u"toolButtonFlipHorizontal")
        icon28 = QIcon()
        icon28.addFile(u":/toolbar/svgicons/flip-horizontal-2.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonFlipHorizontal.setIcon(icon28)
        self.toolButtonFlipHorizontal.setIconSize(QSize(24, 24))
        self.toolButtonFlipHorizontal.setCheckable(False)
        self.toolButtonFlipHorizontal.setChecked(False)

        self.formLayout.setWidget(9, QFormLayout.FieldRole, self.toolButtonFlipHorizontal)

        self.toolButtonPan = QToolButton(self.gridLayoutWidget)
        self.toolButtonPan.setObjectName(u"toolButtonPan")
        icon29 = QIcon()
        icon29.addFile(u":/toolbar/svgicons/pan-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonPan.setIcon(icon29)
        self.toolButtonPan.setIconSize(QSize(24, 24))
        self.toolButtonPan.setCheckable(False)
        self.toolButtonPan.setChecked(False)

        self.formLayout.setWidget(10, QFormLayout.FieldRole, self.toolButtonPan)

        self.toolButtonChecker_10 = QToolButton(self.gridLayoutWidget)
        self.toolButtonChecker_10.setObjectName(u"toolButtonChecker_10")
        icon30 = QIcon()
        icon30.addFile(u":/toolbar/svgicons/stop.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonChecker_10.setIcon(icon30)
        self.toolButtonChecker_10.setIconSize(QSize(24, 24))
        self.toolButtonChecker_10.setCheckable(False)
        self.toolButtonChecker_10.setChecked(False)

        self.formLayout.setWidget(11, QFormLayout.FieldRole, self.toolButtonChecker_10)

        self.toolButtonChecker_11 = QToolButton(self.gridLayoutWidget)
        self.toolButtonChecker_11.setObjectName(u"toolButtonChecker_11")
        self.toolButtonChecker_11.setIcon(icon30)
        self.toolButtonChecker_11.setIconSize(QSize(24, 24))
        self.toolButtonChecker_11.setCheckable(False)
        self.toolButtonChecker_11.setChecked(False)

        self.formLayout.setWidget(12, QFormLayout.FieldRole, self.toolButtonChecker_11)

        self.toolButtonChecker_13 = QToolButton(self.gridLayoutWidget)
        self.toolButtonChecker_13.setObjectName(u"toolButtonChecker_13")
        self.toolButtonChecker_13.setIcon(icon30)
        self.toolButtonChecker_13.setIconSize(QSize(24, 24))
        self.toolButtonChecker_13.setCheckable(False)
        self.toolButtonChecker_13.setChecked(False)

        self.formLayout.setWidget(12, QFormLayout.LabelRole, self.toolButtonChecker_13)

        self.toolButtonChecker_14 = QToolButton(self.gridLayoutWidget)
        self.toolButtonChecker_14.setObjectName(u"toolButtonChecker_14")
        self.toolButtonChecker_14.setIcon(icon30)
        self.toolButtonChecker_14.setIconSize(QSize(24, 24))
        self.toolButtonChecker_14.setCheckable(False)
        self.toolButtonChecker_14.setChecked(False)

        self.formLayout.setWidget(13, QFormLayout.FieldRole, self.toolButtonChecker_14)

        self.toolButtonZoomOut = QToolButton(self.gridLayoutWidget)
        self.toolButtonZoomOut.setObjectName(u"toolButtonZoomOut")
        icon31 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomOut))
        self.toolButtonZoomOut.setIcon(icon31)
        self.toolButtonZoomOut.setIconSize(QSize(24, 24))
        self.toolButtonZoomOut.setCheckable(False)
        self.toolButtonZoomOut.setChecked(False)

        self.formLayout.setWidget(7, QFormLayout.LabelRole, self.toolButtonZoomOut)

        self.toolButtonMirror = QToolButton(self.gridLayoutWidget)
        self.toolButtonMirror.setObjectName(u"toolButtonMirror")
        icon32 = QIcon()
        icon32.addFile(u":/toolbar/svgicons/rays.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonMirror.setIcon(icon32)
        self.toolButtonMirror.setIconSize(QSize(24, 24))
        self.toolButtonMirror.setCheckable(False)
        self.toolButtonMirror.setChecked(False)

        self.formLayout.setWidget(8, QFormLayout.LabelRole, self.toolButtonMirror)

        self.toolButtonFlipVertical = QToolButton(self.gridLayoutWidget)
        self.toolButtonFlipVertical.setObjectName(u"toolButtonFlipVertical")
        icon33 = QIcon()
        icon33.addFile(u":/toolbar/svgicons/flip-vertical-2.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonFlipVertical.setIcon(icon33)
        self.toolButtonFlipVertical.setIconSize(QSize(24, 24))
        self.toolButtonFlipVertical.setCheckable(False)
        self.toolButtonFlipVertical.setChecked(False)

        self.formLayout.setWidget(9, QFormLayout.LabelRole, self.toolButtonFlipVertical)

        self.toolButtonSelectLasso = QToolButton(self.gridLayoutWidget)
        self.toolButtonSelectLasso.setObjectName(u"toolButtonSelectLasso")
        icon34 = QIcon()
        icon34.addFile(u":/toolbar/svgicons/lasso_select.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonSelectLasso.setIcon(icon34)
        self.toolButtonSelectLasso.setIconSize(QSize(24, 24))
        self.toolButtonSelectLasso.setCheckable(False)
        self.toolButtonSelectLasso.setChecked(False)

        self.formLayout.setWidget(10, QFormLayout.LabelRole, self.toolButtonSelectLasso)

        self.toolButtonChecker = QToolButton(self.gridLayoutWidget)
        self.toolButtonChecker.setObjectName(u"toolButtonChecker")
        icon35 = QIcon()
        icon35.addFile(u":/checker/checker20.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonChecker.setIcon(icon35)
        self.toolButtonChecker.setIconSize(QSize(24, 24))
        self.toolButtonChecker.setCheckable(False)
        self.toolButtonChecker.setChecked(False)

        self.formLayout.setWidget(11, QFormLayout.LabelRole, self.toolButtonChecker)

        self.toolButtonGradient = QToolButton(self.gridLayoutWidget)
        self.toolButtonGradient.setObjectName(u"toolButtonGradient")
        icon36 = QIcon()
        icon36.addFile(u":/toolbar/svgicons/gradient.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonGradient.setIcon(icon36)
        self.toolButtonGradient.setIconSize(QSize(24, 24))
        self.toolButtonGradient.setCheckable(False)
        self.toolButtonGradient.setChecked(False)

        self.formLayout.setWidget(13, QFormLayout.LabelRole, self.toolButtonGradient)

        self.label_6 = QLabel(self.dockWidgetContents)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 480, 49, 16))
        self.dwTools.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dwTools)
        self.dwColorBox = QDockWidget(MainWindow)
        self.dwColorBox.setObjectName(u"dwColorBox")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.dwColorBox.sizePolicy().hasHeightForWidth())
        self.dwColorBox.setSizePolicy(sizePolicy4)
        icon37 = QIcon()
        icon37.addFile(u":/toolbar/svgicons/colorbox.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.dwColorBox.setWindowIcon(icon37)
        self.dockWidgetColors = QWidget()
        self.dockWidgetColors.setObjectName(u"dockWidgetColors")
        self.verticalLayout = QVBoxLayout(self.dockWidgetColors)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.widgetColors = QGraphicsView(self.dockWidgetColors)
        self.widgetColors.setObjectName(u"widgetColors")
        self.widgetColors.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(157, 157, 157, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widgetColors.setFrameShape(QFrame.Shape.Panel)
        self.widgetColors.setFrameShadow(QFrame.Shadow.Plain)
        self.widgetColors.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.verticalLayout.addWidget(self.widgetColors)

        self.dwColorBox.setWidget(self.dockWidgetColors)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dwColorBox)
        self.dwToolProperties = QDockWidget(MainWindow)
        self.dwToolProperties.setObjectName(u"dwToolProperties")
        self.dwToolProperties.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.dwToolProperties.setFeatures(QDockWidget.DockWidgetFeature.NoDockWidgetFeatures)
        self.dwToolProperties.setAllowedAreas(Qt.DockWidgetArea.BottomDockWidgetArea)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.verticalLayout_3 = QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.horizontalSlider_2 = QSlider(self.dockWidgetContents_2)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout.addWidget(self.horizontalSlider_2, 2, 6, 1, 1)

        self.label_3 = QLabel(self.dockWidgetContents_2)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout.addWidget(self.label_3, 2, 8, 1, 1)

        self.label_5 = QLabel(self.dockWidgetContents_2)
        self.label_5.setObjectName(u"label_5")

        self.gridLayout.addWidget(self.label_5, 1, 8, 1, 1)

        self.spinBox_3 = QSpinBox(self.dockWidgetContents_2)
        self.spinBox_3.setObjectName(u"spinBox_3")

        self.gridLayout.addWidget(self.spinBox_3, 2, 10, 1, 1)

        self.checkBox = QCheckBox(self.dockWidgetContents_2)
        self.checkBox.setObjectName(u"checkBox")

        self.gridLayout.addWidget(self.checkBox, 2, 11, 1, 1)

        self.spinBox_2 = QSpinBox(self.dockWidgetContents_2)
        self.spinBox_2.setObjectName(u"spinBox_2")

        self.gridLayout.addWidget(self.spinBox_2, 2, 7, 1, 1)

        self.horizontalSlider_3 = QSlider(self.dockWidgetContents_2)
        self.horizontalSlider_3.setObjectName(u"horizontalSlider_3")
        self.horizontalSlider_3.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout.addWidget(self.horizontalSlider_3, 2, 9, 1, 1)

        self.spinBox_1 = QSpinBox(self.dockWidgetContents_2)
        self.spinBox_1.setObjectName(u"spinBox_1")
        self.spinBox_1.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_1.setAccelerated(True)
        self.spinBox_1.setMaximum(600)
        self.spinBox_1.setStepType(QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.spinBox_1.setDisplayIntegerBase(10)

        self.gridLayout.addWidget(self.spinBox_1, 1, 3, 1, 1)

        self.horizontalSlider_1 = QSlider(self.dockWidgetContents_2)
        self.horizontalSlider_1.setObjectName(u"horizontalSlider_1")
        self.horizontalSlider_1.setMinimum(1)
        self.horizontalSlider_1.setMaximum(600)
        self.horizontalSlider_1.setPageStep(50)
        self.horizontalSlider_1.setTracking(True)
        self.horizontalSlider_1.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSlider_1.setInvertedAppearance(False)
        self.horizontalSlider_1.setInvertedControls(False)
        self.horizontalSlider_1.setTickPosition(QSlider.TickPosition.TicksBelow)

        self.gridLayout.addWidget(self.horizontalSlider_1, 1, 2, 1, 1)

        self.label_1 = QLabel(self.dockWidgetContents_2)
        self.label_1.setObjectName(u"label_1")

        self.gridLayout.addWidget(self.label_1, 1, 1, 1, 1)

        self.label = QLabel(self.dockWidgetContents_2)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)

        self.label_2 = QLabel(self.dockWidgetContents_2)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout.addWidget(self.label_2, 2, 4, 1, 1)

        self.horizontalSlider_4 = QSlider(self.dockWidgetContents_2)
        self.horizontalSlider_4.setObjectName(u"horizontalSlider_4")
        self.horizontalSlider_4.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout.addWidget(self.horizontalSlider_4, 1, 6, 1, 1)

        self.label_4 = QLabel(self.dockWidgetContents_2)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout.addWidget(self.label_4, 1, 4, 1, 1)

        self.horizontalSlider_5 = QSlider(self.dockWidgetContents_2)
        self.horizontalSlider_5.setObjectName(u"horizontalSlider_5")
        self.horizontalSlider_5.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout.addWidget(self.horizontalSlider_5, 1, 9, 1, 1)

        self.spinBox = QSpinBox(self.dockWidgetContents_2)
        self.spinBox.setObjectName(u"spinBox")

        self.gridLayout.addWidget(self.spinBox, 2, 3, 1, 1)

        self.spinBox_4 = QSpinBox(self.dockWidgetContents_2)
        self.spinBox_4.setObjectName(u"spinBox_4")

        self.gridLayout.addWidget(self.spinBox_4, 1, 7, 1, 1)

        self.spinBox_5 = QSpinBox(self.dockWidgetContents_2)
        self.spinBox_5.setObjectName(u"spinBox_5")

        self.gridLayout.addWidget(self.spinBox_5, 1, 10, 1, 1)

        self.horizontalSlider_6 = QSlider(self.dockWidgetContents_2)
        self.horizontalSlider_6.setObjectName(u"horizontalSlider_6")
        self.horizontalSlider_6.setOrientation(Qt.Orientation.Horizontal)

        self.gridLayout.addWidget(self.horizontalSlider_6, 2, 2, 1, 1)


        self.verticalLayout_3.addLayout(self.gridLayout)

        self.dwToolProperties.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.dwToolProperties)
        self.dockWidgetLayers = QDockWidget(MainWindow)
        self.dockWidgetLayers.setObjectName(u"dockWidgetLayers")
        icon38 = QIcon()
        icon38.addFile(u":/toolbar/svgicons/red_blue_drawers.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.dockWidgetLayers.setWindowIcon(icon38)
        self.dockWidgetContents_3 = QWidget()
        self.dockWidgetContents_3.setObjectName(u"dockWidgetContents_3")
        self.horizontalLayoutWidget = QWidget(self.dockWidgetContents_3)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(11, 11, 258, 226))
        self.verticalLayout_2 = QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.treeWidget = QTreeWidget(self.horizontalLayoutWidget)
        icon39 = QIcon()
        icon39.addFile(u":/toolbar/svgicons/visible-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon40 = QIcon()
        icon40.addFile(u":/toolbar/svgicons/opaque.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon41 = QIcon()
        icon41.addFile(u":/toolbar/svgicons/unlock.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        font = QFont()
        font.setKerning(False)
        __qtreewidgetitem = QTreeWidgetItem(self.treeWidget)
        __qtreewidgetitem.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEditable|Qt.ItemIsEnabled);
        __qtreewidgetitem.setFont(2, font);
        __qtreewidgetitem.setIcon(2, icon41);
        __qtreewidgetitem.setIcon(1, icon40);
        __qtreewidgetitem.setIcon(0, icon39);
        self.treeWidget.setObjectName(u"treeWidget")

        self.verticalLayout_2.addWidget(self.treeWidget)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.toolButton_3 = QToolButton(self.horizontalLayoutWidget)
        self.toolButton_3.setObjectName(u"toolButton_3")
        icon42 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListAdd))
        self.toolButton_3.setIcon(icon42)

        self.horizontalLayout_2.addWidget(self.toolButton_3)

        self.toolButton_2 = QToolButton(self.horizontalLayoutWidget)
        self.toolButton_2.setObjectName(u"toolButton_2")
        icon43 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListRemove))
        self.toolButton_2.setIcon(icon43)

        self.horizontalLayout_2.addWidget(self.toolButton_2)

        self.toolButton_4 = QToolButton(self.horizontalLayoutWidget)
        self.toolButton_4.setObjectName(u"toolButton_4")
        self.toolButton_4.setIcon(icon6)

        self.horizontalLayout_2.addWidget(self.toolButton_4)

        self.toolButton = QToolButton(self.horizontalLayoutWidget)
        self.toolButton.setObjectName(u"toolButton")
        icon44 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoUp))
        self.toolButton.setIcon(icon44)

        self.horizontalLayout_2.addWidget(self.toolButton)

        self.toolButton_5 = QToolButton(self.horizontalLayoutWidget)
        self.toolButton_5.setObjectName(u"toolButton_5")
        icon45 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoDown))
        self.toolButton_5.setIcon(icon45)

        self.horizontalLayout_2.addWidget(self.toolButton_5)

        self.toolButton_7 = QToolButton(self.horizontalLayoutWidget)
        self.toolButton_7.setObjectName(u"toolButton_7")
        icon46 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.WindowNew))
        self.toolButton_7.setIcon(icon46)

        self.horizontalLayout_2.addWidget(self.toolButton_7)

        self.toolButton_6 = QToolButton(self.horizontalLayoutWidget)
        self.toolButton_6.setObjectName(u"toolButton_6")
        icon47 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentProperties))
        self.toolButton_6.setIcon(icon47)

        self.horizontalLayout_2.addWidget(self.toolButton_6)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.dockWidgetLayers.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockWidgetLayers)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuFilters.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionPrint)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuTools.addAction(self.actionPen)
        self.menuTools.addAction(self.actionLine)
        self.menuTools.addAction(self.actionRectangle)
        self.menuTools.addAction(self.actionEllipse)
        self.menuTools.addAction(self.actionSpray)
        self.menuTools.addAction(self.actionFill)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionTest)

        self.retranslateUi(MainWindow)
        self.horizontalSlider_1.valueChanged.connect(self.spinBox_1.setValue)
        self.spinBox_1.valueChanged.connect(self.horizontalSlider_1.setValue)
        self.horizontalSlider_2.valueChanged.connect(self.spinBox_2.setValue)
        self.spinBox_2.valueChanged.connect(self.horizontalSlider_2.setValue)
        self.horizontalSlider_3.valueChanged.connect(self.spinBox_3.setValue)
        self.spinBox_3.valueChanged.connect(self.horizontalSlider_3.setValue)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionPen.setText(QCoreApplication.translate("MainWindow", u"Pen", None))
        self.actionLine.setText(QCoreApplication.translate("MainWindow", u"Line", None))
        self.actionRectangle.setText(QCoreApplication.translate("MainWindow", u"Rectangle", None))
        self.actionEllipse.setText(QCoreApplication.translate("MainWindow", u"Ellipse", None))
        self.actionSpray.setText(QCoreApplication.translate("MainWindow", u"Spray", None))
        self.actionFill.setText(QCoreApplication.translate("MainWindow", u"Fill", None))
        self.actionTest.setText(QCoreApplication.translate("MainWindow", u"Test", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuImage.setTitle(QCoreApplication.translate("MainWindow", u"Image", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuFilters.setTitle(QCoreApplication.translate("MainWindow", u"Filters", None))
#if QT_CONFIG(statustip)
        self.statusbar.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.toolButtonBrush.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonFill.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonLine.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonRect.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonCircle.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonPen.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonSelectRectangle.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(accessibility)
        self.toolButtonSelectCircle.setAccessibleName(QCoreApplication.translate("MainWindow", u"\u00c7ember", None))
#endif // QT_CONFIG(accessibility)
        self.toolButtonSelectCircle.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonWand.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonRoundRect.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonSpray.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonEraser.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonText.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonDropper.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonZoomIn.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonZoomReset.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonFlipHorizontal.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonPan.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonChecker_10.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonChecker_11.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonChecker_13.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonChecker_14.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonZoomOut.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonMirror.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonFlipVertical.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonSelectLasso.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonChecker.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonGradient.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.dwColorBox.setWindowTitle(QCoreApplication.translate("MainWindow", u"Colors", None))
        self.dwToolProperties.setWindowTitle("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Density", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Opacity", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"CheckBox", None))
        self.label_1.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Radius", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Hardness", None))
        self.dockWidgetLayers.setWindowTitle(QCoreApplication.translate("MainWindow", u"Layers", None))
        ___qtreewidgetitem = self.treeWidget.headerItem()
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("MainWindow", u"Locked", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("MainWindow", u"Layer", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"Visible", None));

        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        ___qtreewidgetitem1 = self.treeWidget.topLevelItem(0)
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("MainWindow", u"Background", None));
        self.treeWidget.setSortingEnabled(__sortingEnabled)

        self.toolButton_3.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_2.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_4.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_5.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_7.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_6.setText(QCoreApplication.translate("MainWindow", u"...", None))
    # retranslateUi

