# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QAbstractSpinBox, QApplication, QDockWidget,
    QFrame, QGraphicsView, QGridLayout, QHBoxLayout,
    QHeaderView, QLabel, QLayout, QMainWindow,
    QMenu, QMenuBar, QScrollArea, QSizePolicy,
    QSlider, QSpacerItem, QSpinBox, QStatusBar,
    QTabWidget, QToolBar, QToolButton, QTreeWidget,
    QTreeWidgetItem, QVBoxLayout, QWidget)
import svgicons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1056, 911)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        icon = QIcon()
        icon.addFile(u"svgicons/hcie.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon1 = QIcon()
        icon1.addFile(u"svgicons/new.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNew.setIcon(icon1)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon2 = QIcon()
        icon2.addFile(u"svgicons/open-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpen.setIcon(icon2)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon3 = QIcon()
        icon3.addFile(u"svgicons/save-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave.setIcon(icon3)
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        icon4 = QIcon()
        icon4.addFile(u"svgicons/print.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrint.setIcon(icon4)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon5 = QIcon()
        icon5.addFile(u"svgicons/cut.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCut.setIcon(icon5)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon6 = QIcon()
        icon6.addFile(u"svgicons/copy.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCopy.setIcon(icon6)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon7 = QIcon()
        icon7.addFile(u"svgicons/paste-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPaste.setIcon(icon7)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon8 = QIcon()
        icon8.addFile(u"svgicons/undo-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionUndo.setIcon(icon8)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon9 = QIcon()
        icon9.addFile(u"svgicons/redo-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRedo.setIcon(icon9)
        self.actionPen = QAction(MainWindow)
        self.actionPen.setObjectName(u"actionPen")
        icon10 = QIcon()
        icon10.addFile(u":/toolbar/svgicons/pen.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPen.setIcon(icon10)
        self.actionLine = QAction(MainWindow)
        self.actionLine.setObjectName(u"actionLine")
        icon11 = QIcon()
        icon11.addFile(u":/toolbar/svgicons/line-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLine.setIcon(icon11)
        self.actionRectangle = QAction(MainWindow)
        self.actionRectangle.setObjectName(u"actionRectangle")
        self.actionEllipse = QAction(MainWindow)
        self.actionEllipse.setObjectName(u"actionEllipse")
        self.actionSpray = QAction(MainWindow)
        self.actionSpray.setObjectName(u"actionSpray")
        self.actionFill = QAction(MainWindow)
        self.actionFill.setObjectName(u"actionFill")
        self.actionTest = QAction(MainWindow)
        self.actionTest.setObjectName(u"actionTest")
        icon12 = QIcon()
        icon12.addFile(u"svgicons/monitor.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTest.setIcon(icon12)
        self.actionTest.setMenuRole(QAction.MenuRole.NoRole)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon13 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ApplicationExit))
        self.actionExit.setIcon(icon13)
        self.actionSepia = QAction(MainWindow)
        self.actionSepia.setObjectName(u"actionSepia")
        self.actionPixelate = QAction(MainWindow)
        self.actionPixelate.setObjectName(u"actionPixelate")
        self.actionBlur_2 = QAction(MainWindow)
        self.actionBlur_2.setObjectName(u"actionBlur_2")
        self.actionAntialias = QAction(MainWindow)
        self.actionAntialias.setObjectName(u"actionAntialias")
        self.actionMelt = QAction(MainWindow)
        self.actionMelt.setObjectName(u"actionMelt")
        self.actionMosaic = QAction(MainWindow)
        self.actionMosaic.setObjectName(u"actionMosaic")
        self.actionShear = QAction(MainWindow)
        self.actionShear.setObjectName(u"actionShear")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.verticalLayout_4 = QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.scrollArea = QScrollArea(self.tab)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 754, 725))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy1)
        self.gridLayout_2 = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.widgetPicture1 = QFrame(self.scrollAreaWidgetContents)
        self.widgetPicture1.setObjectName(u"widgetPicture1")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.widgetPicture1.sizePolicy().hasHeightForWidth())
        self.widgetPicture1.setSizePolicy(sizePolicy2)
        self.widgetPicture1.setMinimumSize(QSize(100, 100))
        self.widgetPicture1.setMaximumSize(QSize(16777215, 16777215))
        self.widgetPicture1.setMouseTracking(True)
        self.widgetPicture1.setTabletTracking(True)
        self.widgetPicture1.setAutoFillBackground(False)
        self.widgetPicture1.setStyleSheet(u"background-image: url(:/checker/checker20.png);")

        self.gridLayout_2.addWidget(self.widgetPicture1, 0, 0, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_4.addWidget(self.scrollArea)

        self.tabWidget.addTab(self.tab, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1056, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuImage = QMenu(self.menubar)
        self.menuImage.setObjectName(u"menuImage")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuFilters = QMenu(self.menubar)
        self.menuFilters.setObjectName(u"menuFilters")
        self.menuBlur = QMenu(self.menuFilters)
        self.menuBlur.setObjectName(u"menuBlur")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setMinimumSize(QSize(50, 50))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy3)
        self.toolBar.setMaximumSize(QSize(16777215, 500))
        self.toolBar.setMouseTracking(True)
        self.toolBar.setTabletTracking(True)
        self.toolBar.setStyleSheet(u"border-color: rgb(255, 0, 255);")
        self.toolBar.setAllowedAreas(Qt.ToolBarArea.NoToolBarArea)
        self.toolBar.setIconSize(QSize(28, 28))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.dwTools = QDockWidget(MainWindow)
        self.dwTools.setObjectName(u"dwTools")
        sizePolicy3.setHeightForWidth(self.dwTools.sizePolicy().hasHeightForWidth())
        self.dwTools.setSizePolicy(sizePolicy3)
        self.dwTools.setMinimumSize(QSize(100, 300))
        self.dwTools.setMaximumSize(QSize(100, 316))
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.dockWidgetContents.setMinimumSize(QSize(100, 200))
        self.dockWidgetContents.setMaximumSize(QSize(100, 300))
        self.verticalLayout_2 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.toolButtonChecker_11 = QToolButton(self.dockWidgetContents)
        self.toolButtonChecker_11.setObjectName(u"toolButtonChecker_11")
        icon14 = QIcon()
        icon14.addFile(u"svgicons/warning.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonChecker_11.setIcon(icon14)
        self.toolButtonChecker_11.setIconSize(QSize(24, 24))
        self.toolButtonChecker_11.setCheckable(False)
        self.toolButtonChecker_11.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonChecker_11, 13, 1, 1, 1)

        self.toolButtonPen = QToolButton(self.dockWidgetContents)
        self.toolButtonPen.setObjectName(u"toolButtonPen")
        icon15 = QIcon()
        icon15.addFile(u":/darksvg/resources/themes/ie_dark/pen.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonPen.setIcon(icon15)
        self.toolButtonPen.setIconSize(QSize(24, 24))
        self.toolButtonPen.setCheckable(False)
        self.toolButtonPen.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonPen, 0, 0, 1, 1)

        self.toolButtonDropper = QToolButton(self.dockWidgetContents)
        self.toolButtonDropper.setObjectName(u"toolButtonDropper")
        self.toolButtonDropper.setMouseTracking(True)
        self.toolButtonDropper.setTabletTracking(True)
        icon16 = QIcon()
        icon16.addFile(u"svgicons/dropper.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonDropper.setIcon(icon16)
        self.toolButtonDropper.setIconSize(QSize(24, 24))
        self.toolButtonDropper.setCheckable(True)
        self.toolButtonDropper.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonDropper, 8, 0, 1, 1)

        self.toolButtonWand = QToolButton(self.dockWidgetContents)
        self.toolButtonWand.setObjectName(u"toolButtonWand")
        icon17 = QIcon()
        icon17.addFile(u"svgicons/magic.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonWand.setIcon(icon17)
        self.toolButtonWand.setIconSize(QSize(24, 24))

        self.gridLayout_3.addWidget(self.toolButtonWand, 4, 0, 1, 1)

        self.toolButtonSelectionLasso = QToolButton(self.dockWidgetContents)
        self.toolButtonSelectionLasso.setObjectName(u"toolButtonSelectionLasso")
        icon18 = QIcon()
        icon18.addFile(u"svgicons/lasso_select.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonSelectionLasso.setIcon(icon18)
        self.toolButtonSelectionLasso.setIconSize(QSize(24, 24))
        self.toolButtonSelectionLasso.setCheckable(False)
        self.toolButtonSelectionLasso.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonSelectionLasso, 7, 0, 1, 1)

        self.toolButtonZoomOut = QToolButton(self.dockWidgetContents)
        self.toolButtonZoomOut.setObjectName(u"toolButtonZoomOut")
        icon19 = QIcon()
        icon19.addFile(u"svgicons/zoomout-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonZoomOut.setIcon(icon19)
        self.toolButtonZoomOut.setIconSize(QSize(24, 24))
        self.toolButtonZoomOut.setCheckable(False)
        self.toolButtonZoomOut.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonZoomOut, 9, 0, 1, 1)

        self.toolButtonRoundRectangle = QToolButton(self.dockWidgetContents)
        self.toolButtonRoundRectangle.setObjectName(u"toolButtonRoundRectangle")
        icon20 = QIcon()
        icon20.addFile(u"svgicons/rounded-rectangle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonRoundRectangle.setIcon(icon20)
        self.toolButtonRoundRectangle.setIconSize(QSize(24, 24))

        self.gridLayout_3.addWidget(self.toolButtonRoundRectangle, 1, 2, 1, 1)

        self.toolButtonSelectionCircle = QToolButton(self.dockWidgetContents)
        self.toolButtonSelectionCircle.setObjectName(u"toolButtonSelectionCircle")
        icon21 = QIcon()
        icon21.addFile(u"svgicons/select-circle-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonSelectionCircle.setIcon(icon21)
        self.toolButtonSelectionCircle.setIconSize(QSize(24, 24))

        self.gridLayout_3.addWidget(self.toolButtonSelectionCircle, 4, 2, 1, 1)

        self.toolButtonCrop = QToolButton(self.dockWidgetContents)
        self.toolButtonCrop.setObjectName(u"toolButtonCrop")
        icon22 = QIcon()
        icon22.addFile(u"svgicons/crop.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonCrop.setIcon(icon22)
        self.toolButtonCrop.setIconSize(QSize(24, 24))
        self.toolButtonCrop.setCheckable(False)
        self.toolButtonCrop.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonCrop, 7, 2, 1, 1)

        self.toolButtonChecker = QToolButton(self.dockWidgetContents)
        self.toolButtonChecker.setObjectName(u"toolButtonChecker")
        icon23 = QIcon()
        icon23.addFile(u"svgicons/checker.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonChecker.setIcon(icon23)
        self.toolButtonChecker.setIconSize(QSize(24, 24))
        self.toolButtonChecker.setCheckable(False)
        self.toolButtonChecker.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonChecker, 11, 2, 1, 1)

        self.toolButtonRectangle = QToolButton(self.dockWidgetContents)
        self.toolButtonRectangle.setObjectName(u"toolButtonRectangle")
        icon24 = QIcon()
        icon24.addFile(u"svgicons/rectangle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonRectangle.setIcon(icon24)
        self.toolButtonRectangle.setIconSize(QSize(24, 24))
        self.toolButtonRectangle.setCheckable(False)
        self.toolButtonRectangle.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonRectangle, 1, 1, 1, 1)

        self.toolButtonSpray = QToolButton(self.dockWidgetContents)
        self.toolButtonSpray.setObjectName(u"toolButtonSpray")
        icon25 = QIcon()
        icon25.addFile(u"svgicons/spray-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonSpray.setIcon(icon25)
        self.toolButtonSpray.setIconSize(QSize(24, 24))
        self.toolButtonSpray.setCheckable(False)
        self.toolButtonSpray.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonSpray, 3, 1, 1, 1)

        self.toolButtonFlipHorizontal = QToolButton(self.dockWidgetContents)
        self.toolButtonFlipHorizontal.setObjectName(u"toolButtonFlipHorizontal")
        icon26 = QIcon()
        icon26.addFile(u"svgicons/flip-horizontal-3.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonFlipHorizontal.setIcon(icon26)
        self.toolButtonFlipHorizontal.setIconSize(QSize(24, 24))
        self.toolButtonFlipHorizontal.setCheckable(False)
        self.toolButtonFlipHorizontal.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonFlipHorizontal, 11, 1, 1, 1)

        self.toolButtonChecker_14 = QToolButton(self.dockWidgetContents)
        self.toolButtonChecker_14.setObjectName(u"toolButtonChecker_14")
        self.toolButtonChecker_14.setIcon(icon14)
        self.toolButtonChecker_14.setIconSize(QSize(24, 24))
        self.toolButtonChecker_14.setCheckable(False)
        self.toolButtonChecker_14.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonChecker_14, 13, 2, 1, 1)

        self.toolButtonMirror = QToolButton(self.dockWidgetContents)
        self.toolButtonMirror.setObjectName(u"toolButtonMirror")
        icon27 = QIcon()
        icon27.addFile(u"svgicons/rays.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonMirror.setIcon(icon27)
        self.toolButtonMirror.setIconSize(QSize(24, 24))
        self.toolButtonMirror.setCheckable(False)
        self.toolButtonMirror.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonMirror, 8, 2, 1, 1)

        self.toolButtonPan = QToolButton(self.dockWidgetContents)
        self.toolButtonPan.setObjectName(u"toolButtonPan")
        icon28 = QIcon()
        icon28.addFile(u"svgicons/pan-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonPan.setIcon(icon28)
        self.toolButtonPan.setIconSize(QSize(24, 24))
        self.toolButtonPan.setCheckable(False)
        self.toolButtonPan.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonPan, 8, 1, 1, 1)

        self.toolButtonCircle = QToolButton(self.dockWidgetContents)
        self.toolButtonCircle.setObjectName(u"toolButtonCircle")
        icon29 = QIcon()
        icon29.addFile(u"svgicons/circle-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonCircle.setIcon(icon29)
        self.toolButtonCircle.setIconSize(QSize(24, 24))
        self.toolButtonCircle.setCheckable(False)
        self.toolButtonCircle.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonCircle, 3, 0, 1, 1)

        self.toolButtonGradient = QToolButton(self.dockWidgetContents)
        self.toolButtonGradient.setObjectName(u"toolButtonGradient")
        icon30 = QIcon()
        icon30.addFile(u"svgicons/gradient.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonGradient.setIcon(icon30)
        self.toolButtonGradient.setIconSize(QSize(24, 24))
        self.toolButtonGradient.setCheckable(False)
        self.toolButtonGradient.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonGradient, 14, 0, 1, 1)

        self.toolButtonText = QToolButton(self.dockWidgetContents)
        self.toolButtonText.setObjectName(u"toolButtonText")
        icon31 = QIcon()
        icon31.addFile(u"svgicons/text.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonText.setIcon(icon31)
        self.toolButtonText.setIconSize(QSize(24, 24))

        self.gridLayout_3.addWidget(self.toolButtonText, 7, 1, 1, 1)

        self.toolButtonZoomIn = QToolButton(self.dockWidgetContents)
        self.toolButtonZoomIn.setObjectName(u"toolButtonZoomIn")
        icon32 = QIcon()
        icon32.addFile(u"svgicons/zoomin-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonZoomIn.setIcon(icon32)
        self.toolButtonZoomIn.setIconSize(QSize(24, 24))
        self.toolButtonZoomIn.setCheckable(False)
        self.toolButtonZoomIn.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonZoomIn, 9, 1, 1, 1)

        self.toolButtonZoomReset = QToolButton(self.dockWidgetContents)
        self.toolButtonZoomReset.setObjectName(u"toolButtonZoomReset")
        icon33 = QIcon()
        icon33.addFile(u"svgicons/zoom_reset.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonZoomReset.setIcon(icon33)
        self.toolButtonZoomReset.setIconSize(QSize(24, 24))
        self.toolButtonZoomReset.setCheckable(False)
        self.toolButtonZoomReset.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonZoomReset, 9, 2, 1, 1)

        self.toolButtonSelectionRectangle = QToolButton(self.dockWidgetContents)
        self.toolButtonSelectionRectangle.setObjectName(u"toolButtonSelectionRectangle")
        icon34 = QIcon()
        icon34.addFile(u"svgicons/select-rectangle-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonSelectionRectangle.setIcon(icon34)
        self.toolButtonSelectionRectangle.setIconSize(QSize(24, 24))

        self.gridLayout_3.addWidget(self.toolButtonSelectionRectangle, 4, 1, 1, 1)

        self.toolButtonLine = QToolButton(self.dockWidgetContents)
        self.toolButtonLine.setObjectName(u"toolButtonLine")
        self.toolButtonLine.setMouseTracking(True)
        self.toolButtonLine.setTabletTracking(True)
        icon35 = QIcon()
        icon35.addFile(u"svgicons/line-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonLine.setIcon(icon35)
        self.toolButtonLine.setIconSize(QSize(24, 24))
        self.toolButtonLine.setCheckable(False)
        self.toolButtonLine.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonLine, 1, 0, 1, 1)

        self.toolButtonEraser = QToolButton(self.dockWidgetContents)
        self.toolButtonEraser.setObjectName(u"toolButtonEraser")
        icon36 = QIcon()
        icon36.addFile(u"svgicons/eraser-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonEraser.setIcon(icon36)
        self.toolButtonEraser.setIconSize(QSize(24, 24))

        self.gridLayout_3.addWidget(self.toolButtonEraser, 0, 2, 1, 1)

        self.toolButtonBrush = QToolButton(self.dockWidgetContents)
        self.toolButtonBrush.setObjectName(u"toolButtonBrush")
        icon37 = QIcon()
        icon37.addFile(u"svgicons/brush.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonBrush.setIcon(icon37)
        self.toolButtonBrush.setIconSize(QSize(24, 24))
        self.toolButtonBrush.setCheckable(False)
        self.toolButtonBrush.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonBrush, 0, 1, 1, 1)

        self.toolButtonFill = QToolButton(self.dockWidgetContents)
        self.toolButtonFill.setObjectName(u"toolButtonFill")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.toolButtonFill.sizePolicy().hasHeightForWidth())
        self.toolButtonFill.setSizePolicy(sizePolicy4)
        icon38 = QIcon()
        icon38.addFile(u"svgicons/fill.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonFill.setIcon(icon38)
        self.toolButtonFill.setIconSize(QSize(24, 24))
        self.toolButtonFill.setCheckable(False)
        self.toolButtonFill.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonFill, 3, 2, 1, 1)

        self.toolButtonFlipVertical = QToolButton(self.dockWidgetContents)
        self.toolButtonFlipVertical.setObjectName(u"toolButtonFlipVertical")
        icon39 = QIcon()
        icon39.addFile(u"svgicons/flip-vertical-3.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonFlipVertical.setIcon(icon39)
        self.toolButtonFlipVertical.setIconSize(QSize(24, 24))
        self.toolButtonFlipVertical.setCheckable(False)
        self.toolButtonFlipVertical.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonFlipVertical, 11, 0, 1, 1)

        self.toolButtonCircleOutline = QToolButton(self.dockWidgetContents)
        self.toolButtonCircleOutline.setObjectName(u"toolButtonCircleOutline")
        icon40 = QIcon()
        icon40.addFile(u":/lightsvg/resources/themes/ie_light/circle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolButtonCircleOutline.setIcon(icon40)
        self.toolButtonCircleOutline.setIconSize(QSize(24, 24))
        self.toolButtonCircleOutline.setCheckable(False)
        self.toolButtonCircleOutline.setChecked(False)

        self.gridLayout_3.addWidget(self.toolButtonCircleOutline, 13, 0, 1, 1)


        self.verticalLayout_2.addLayout(self.gridLayout_3)

        self.dwTools.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dwTools)
        self.dwColorBox = QDockWidget(MainWindow)
        self.dwColorBox.setObjectName(u"dwColorBox")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.dwColorBox.sizePolicy().hasHeightForWidth())
        self.dwColorBox.setSizePolicy(sizePolicy5)
        self.dwColorBox.setMinimumSize(QSize(150, 250))
        self.dwColorBox.setMaximumSize(QSize(150, 300))
        icon41 = QIcon()
        icon41.addFile(u"svgicons/colorbox.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.dwColorBox.setWindowIcon(icon41)
        self.dockWidgetColors = QWidget()
        self.dockWidgetColors.setObjectName(u"dockWidgetColors")
        self.verticalLayout = QVBoxLayout(self.dockWidgetColors)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.widgetColors = QGraphicsView(self.dockWidgetColors)
        self.widgetColors.setObjectName(u"widgetColors")
        self.widgetColors.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(157, 157, 157, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widgetColors.setFrameShape(QFrame.Shape.NoFrame)

        self.verticalLayout.addWidget(self.widgetColors)

        self.dwColorBox.setWidget(self.dockWidgetColors)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dwColorBox)
        self.dockWidgetLayers = QDockWidget(MainWindow)
        self.dockWidgetLayers.setObjectName(u"dockWidgetLayers")
        icon42 = QIcon()
        icon42.addFile(u"svgicons/red_blue_drawers.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.dockWidgetLayers.setWindowIcon(icon42)
        self.dockWidgetContents_3 = QWidget()
        self.dockWidgetContents_3.setObjectName(u"dockWidgetContents_3")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.dockWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_3.setSizePolicy(sizePolicy6)
        self.treeWidget = QTreeWidget(self.dockWidgetContents_3)
        font = QFont()
        font.setBold(False)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setTextAlignment(2, Qt.AlignCenter);
        __qtreewidgetitem.setTextAlignment(1, Qt.AlignCenter);
        __qtreewidgetitem.setTextAlignment(0, Qt.AlignCenter);
        __qtreewidgetitem.setFont(0, font);
        self.treeWidget.setHeaderItem(__qtreewidgetitem)
        icon43 = QIcon()
        icon43.addFile(u"svgicons/visible-gray.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon44 = QIcon()
        icon44.addFile(u"svgicons/opaque.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        font1 = QFont()
        font1.setKerning(True)
        icon45 = QIcon()
        icon45.addFile(u"svgicons/unlock.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        font2 = QFont()
        font2.setBold(False)
        font2.setKerning(False)
        __qtreewidgetitem1 = QTreeWidgetItem(self.treeWidget)
        __qtreewidgetitem1.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEditable|Qt.ItemIsEnabled);
        __qtreewidgetitem1.setFont(2, font2);
        __qtreewidgetitem1.setIcon(2, icon45);
        __qtreewidgetitem1.setFont(1, font1);
        __qtreewidgetitem1.setIcon(1, icon44);
        __qtreewidgetitem1.setIcon(0, icon43);
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(-10, 10, 221, 192))
        sizePolicy5.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy5)
        self.treeWidget.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.treeWidget.setIndentation(5)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setMinimumSectionSize(26)
        self.treeWidget.header().setDefaultSectionSize(60)
        self.treeWidget.header().setProperty(u"showSortIndicator", False)
        self.treeWidget.header().setStretchLastSection(True)
        self.toolButton_2 = QToolButton(self.dockWidgetContents_3)
        self.toolButton_2.setObjectName(u"toolButton_2")
        self.toolButton_2.setGeometry(QRect(41, 209, 24, 23))
        icon46 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListRemove))
        self.toolButton_2.setIcon(icon46)
        self.toolButton_6 = QToolButton(self.dockWidgetContents_3)
        self.toolButton_6.setObjectName(u"toolButton_6")
        self.toolButton_6.setGeometry(QRect(191, 209, 24, 23))
        icon47 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentProperties))
        self.toolButton_6.setIcon(icon47)
        self.toolButton_3 = QToolButton(self.dockWidgetContents_3)
        self.toolButton_3.setObjectName(u"toolButton_3")
        self.toolButton_3.setGeometry(QRect(11, 209, 24, 23))
        icon48 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListAdd))
        self.toolButton_3.setIcon(icon48)
        self.toolButton_7 = QToolButton(self.dockWidgetContents_3)
        self.toolButton_7.setObjectName(u"toolButton_7")
        self.toolButton_7.setGeometry(QRect(161, 209, 24, 23))
        icon49 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.WindowNew))
        self.toolButton_7.setIcon(icon49)
        self.toolButton_5 = QToolButton(self.dockWidgetContents_3)
        self.toolButton_5.setObjectName(u"toolButton_5")
        self.toolButton_5.setGeometry(QRect(131, 209, 24, 23))
        icon50 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoDown))
        self.toolButton_5.setIcon(icon50)
        self.toolButton = QToolButton(self.dockWidgetContents_3)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setGeometry(QRect(101, 209, 24, 23))
        icon51 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoUp))
        self.toolButton.setIcon(icon51)
        self.toolButton_4 = QToolButton(self.dockWidgetContents_3)
        self.toolButton_4.setObjectName(u"toolButton_4")
        self.toolButton_4.setGeometry(QRect(71, 209, 24, 23))
        icon52 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditCopy))
        self.toolButton_4.setIcon(icon52)
        self.dockWidgetLayers.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidgetLayers)
        self.dockWidget = QDockWidget(MainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidget.setMinimumSize(QSize(150, 40))
        self.dockWidget.setMaximumSize(QSize(150, 524287))
        self.dockWidgetSliders = QWidget()
        self.dockWidgetSliders.setObjectName(u"dockWidgetSliders")
        self.layoutWidget = QWidget(self.dockWidgetSliders)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(1, 2, 163, 691))
        self.verticalLayout_Top = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_Top.setObjectName(u"verticalLayout_Top")
        self.verticalLayout_Top.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_width = QVBoxLayout()
        self.verticalLayout_width.setObjectName(u"verticalLayout_width")
        self.verticalLayout_width.setContentsMargins(-1, -1, 20, 10)
        self.horizontalLayout_width = QHBoxLayout()
        self.horizontalLayout_width.setObjectName(u"horizontalLayout_width")
        self.label_width = QLabel(self.layoutWidget)
        self.label_width.setObjectName(u"label_width")

        self.horizontalLayout_width.addWidget(self.label_width)

        self.horizontalSpacer_width = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_width.addItem(self.horizontalSpacer_width)

        self.spinBox_width = QSpinBox(self.layoutWidget)
        self.spinBox_width.setObjectName(u"spinBox_width")
        self.spinBox_width.setMaximum(255)

        self.horizontalLayout_width.addWidget(self.spinBox_width)


        self.verticalLayout_width.addLayout(self.horizontalLayout_width)

        self.horizontalLayout_1a_width = QHBoxLayout()
        self.horizontalLayout_1a_width.setObjectName(u"horizontalLayout_1a_width")
        self.horizontalLayout_1a_width.setContentsMargins(-1, 0, -1, 0)
        self.horizontalSlider_width = QSlider(self.layoutWidget)
        self.horizontalSlider_width.setObjectName(u"horizontalSlider_width")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.horizontalSlider_width.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_width.setSizePolicy(sizePolicy7)
        self.horizontalSlider_width.setMinimumSize(QSize(0, 0))
        self.horizontalSlider_width.setMinimum(1)
        self.horizontalSlider_width.setMaximum(600)
        self.horizontalSlider_width.setPageStep(50)
        self.horizontalSlider_width.setTracking(True)
        self.horizontalSlider_width.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSlider_width.setInvertedAppearance(False)
        self.horizontalSlider_width.setInvertedControls(False)
        self.horizontalSlider_width.setTickPosition(QSlider.TickPosition.NoTicks)

        self.horizontalLayout_1a_width.addWidget(self.horizontalSlider_width)


        self.verticalLayout_width.addLayout(self.horizontalLayout_1a_width)


        self.verticalLayout_Top.addLayout(self.verticalLayout_width)

        self.verticalLayout_softness = QVBoxLayout()
        self.verticalLayout_softness.setObjectName(u"verticalLayout_softness")
        self.verticalLayout_softness.setContentsMargins(-1, -1, 20, 10)
        self.horizontalLayout_softness_1 = QHBoxLayout()
        self.horizontalLayout_softness_1.setObjectName(u"horizontalLayout_softness_1")
        self.label_softness = QLabel(self.layoutWidget)
        self.label_softness.setObjectName(u"label_softness")

        self.horizontalLayout_softness_1.addWidget(self.label_softness)

        self.horizontalSpacer_softness = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_softness_1.addItem(self.horizontalSpacer_softness)

        self.spinBox_softness = QSpinBox(self.layoutWidget)
        self.spinBox_softness.setObjectName(u"spinBox_softness")
        self.spinBox_softness.setMaximum(100)

        self.horizontalLayout_softness_1.addWidget(self.spinBox_softness)


        self.verticalLayout_softness.addLayout(self.horizontalLayout_softness_1)

        self.horizontalLayout_softness_2 = QHBoxLayout()
        self.horizontalLayout_softness_2.setObjectName(u"horizontalLayout_softness_2")
        self.horizontalLayout_softness_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalSlider_softness = QSlider(self.layoutWidget)
        self.horizontalSlider_softness.setObjectName(u"horizontalSlider_softness")
        sizePolicy7.setHeightForWidth(self.horizontalSlider_softness.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_softness.setSizePolicy(sizePolicy7)
        self.horizontalSlider_softness.setMaximum(100)
        self.horizontalSlider_softness.setOrientation(Qt.Orientation.Horizontal)

        self.horizontalLayout_softness_2.addWidget(self.horizontalSlider_softness)


        self.verticalLayout_softness.addLayout(self.horizontalLayout_softness_2)


        self.verticalLayout_Top.addLayout(self.verticalLayout_softness)

        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(-1, -1, 20, 10)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")

        self.horizontalLayout_6.addWidget(self.label_5)

        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer_5)

        self.spinBox_opacity = QSpinBox(self.layoutWidget)
        self.spinBox_opacity.setObjectName(u"spinBox_opacity")
        self.spinBox_opacity.setMaximum(100)

        self.horizontalLayout_6.addWidget(self.spinBox_opacity)


        self.verticalLayout_8.addLayout(self.horizontalLayout_6)

        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.horizontalSlider_opacity = QSlider(self.layoutWidget)
        self.horizontalSlider_opacity.setObjectName(u"horizontalSlider_opacity")
        sizePolicy7.setHeightForWidth(self.horizontalSlider_opacity.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_opacity.setSizePolicy(sizePolicy7)
        self.horizontalSlider_opacity.setOrientation(Qt.Orientation.Horizontal)

        self.horizontalLayout_13.addWidget(self.horizontalSlider_opacity)


        self.verticalLayout_8.addLayout(self.horizontalLayout_13)


        self.verticalLayout_Top.addLayout(self.verticalLayout_8)

        self.verticalLayout_9 = QVBoxLayout()
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setObjectName(u"label_6")

        self.horizontalLayout_7.addWidget(self.label_6)

        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_7.addItem(self.horizontalSpacer_6)

        self.spinBox_tolerance = QSpinBox(self.layoutWidget)
        self.spinBox_tolerance.setObjectName(u"spinBox_tolerance")
        self.spinBox_tolerance.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_tolerance.setAccelerated(True)
        self.spinBox_tolerance.setMaximum(600)
        self.spinBox_tolerance.setStepType(QAbstractSpinBox.StepType.DefaultStepType)
        self.spinBox_tolerance.setDisplayIntegerBase(10)

        self.horizontalLayout_7.addWidget(self.spinBox_tolerance)


        self.verticalLayout_9.addLayout(self.horizontalLayout_7)

        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, 0)
        self.horizontalSlider_tolerance = QSlider(self.layoutWidget)
        self.horizontalSlider_tolerance.setObjectName(u"horizontalSlider_tolerance")
        sizePolicy7.setHeightForWidth(self.horizontalSlider_tolerance.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_tolerance.setSizePolicy(sizePolicy7)
        self.horizontalSlider_tolerance.setMaximum(255)
        self.horizontalSlider_tolerance.setPageStep(25)
        self.horizontalSlider_tolerance.setValue(100)
        self.horizontalSlider_tolerance.setOrientation(Qt.Orientation.Horizontal)

        self.horizontalLayout_12.addWidget(self.horizontalSlider_tolerance)


        self.verticalLayout_9.addLayout(self.horizontalLayout_12)


        self.verticalLayout_Top.addLayout(self.verticalLayout_9)

        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(-1, -1, 20, 10)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.label_2_radius = QLabel(self.layoutWidget)
        self.label_2_radius.setObjectName(u"label_2_radius")

        self.horizontalLayout_3.addWidget(self.label_2_radius)

        self.horizontalSpacer_2_radius = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2_radius)

        self.spinBox_2_radius = QSpinBox(self.layoutWidget)
        self.spinBox_2_radius.setObjectName(u"spinBox_2_radius")
        self.spinBox_2_radius.setMaximum(100)

        self.horizontalLayout_3.addWidget(self.spinBox_2_radius)


        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalSlider_radius = QSlider(self.layoutWidget)
        self.horizontalSlider_radius.setObjectName(u"horizontalSlider_radius")
        sizePolicy7.setHeightForWidth(self.horizontalSlider_radius.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_radius.setSizePolicy(sizePolicy7)
        self.horizontalSlider_radius.setOrientation(Qt.Orientation.Horizontal)

        self.horizontalLayout_9.addWidget(self.horizontalSlider_radius)


        self.verticalLayout_5.addLayout(self.horizontalLayout_9)


        self.verticalLayout_Top.addLayout(self.verticalLayout_5)

        self.verticalLayout_density = QVBoxLayout()
        self.verticalLayout_density.setObjectName(u"verticalLayout_density")
        self.verticalLayout_density.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setObjectName(u"label_3")

        self.horizontalLayout_4.addWidget(self.label_3)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_3)

        self.spinBox_density = QSpinBox(self.layoutWidget)
        self.spinBox_density.setObjectName(u"spinBox_density")
        self.spinBox_density.setMaximum(100)

        self.horizontalLayout_4.addWidget(self.spinBox_density)


        self.verticalLayout_density.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalSlider_density = QSlider(self.layoutWidget)
        self.horizontalSlider_density.setObjectName(u"horizontalSlider_density")
        sizePolicy7.setHeightForWidth(self.horizontalSlider_density.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_density.setSizePolicy(sizePolicy7)
        self.horizontalSlider_density.setOrientation(Qt.Orientation.Horizontal)

        self.horizontalLayout_10.addWidget(self.horizontalSlider_density)


        self.verticalLayout_density.addLayout(self.horizontalLayout_10)


        self.verticalLayout_Top.addLayout(self.verticalLayout_density)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_Top.addItem(self.verticalSpacer)

        self.dockWidget.setWidget(self.dockWidgetSliders)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockWidget)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuFilters.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuTools.addAction(self.actionPen)
        self.menuTools.addAction(self.actionLine)
        self.menuTools.addAction(self.actionRectangle)
        self.menuTools.addAction(self.actionEllipse)
        self.menuTools.addAction(self.actionSpray)
        self.menuTools.addAction(self.actionFill)
        self.menuFilters.addAction(self.menuBlur.menuAction())
        self.menuFilters.addAction(self.actionSepia)
        self.menuFilters.addAction(self.actionPixelate)
        self.menuFilters.addAction(self.actionMelt)
        self.menuFilters.addAction(self.actionMosaic)
        self.menuFilters.addAction(self.actionShear)
        self.menuBlur.addAction(self.actionBlur_2)
        self.menuBlur.addAction(self.actionAntialias)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionTest)

        self.retranslateUi(MainWindow)
        self.horizontalSlider_width.valueChanged.connect(self.spinBox_width.setValue)
        self.spinBox_width.valueChanged.connect(self.horizontalSlider_width.setValue)
        self.spinBox_2_radius.valueChanged.connect(self.horizontalSlider_radius.setValue)
        self.horizontalSlider_radius.valueChanged.connect(self.spinBox_2_radius.setValue)
        self.horizontalSlider_density.valueChanged.connect(self.spinBox_density.setValue)
        self.spinBox_density.valueChanged.connect(self.horizontalSlider_density.setValue)
        self.horizontalSlider_softness.valueChanged.connect(self.spinBox_softness.setValue)
        self.spinBox_softness.valueChanged.connect(self.horizontalSlider_softness.setValue)
        self.horizontalSlider_opacity.valueChanged.connect(self.spinBox_opacity.setValue)
        self.spinBox_opacity.valueChanged.connect(self.horizontalSlider_opacity.setValue)
        self.horizontalSlider_tolerance.valueChanged.connect(self.spinBox_tolerance.setValue)
        self.spinBox_tolerance.valueChanged.connect(self.horizontalSlider_tolerance.setValue)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionPen.setText(QCoreApplication.translate("MainWindow", u"Pen", None))
        self.actionLine.setText(QCoreApplication.translate("MainWindow", u"Line", None))
        self.actionRectangle.setText(QCoreApplication.translate("MainWindow", u"Rectangle", None))
        self.actionEllipse.setText(QCoreApplication.translate("MainWindow", u"Ellipse", None))
        self.actionSpray.setText(QCoreApplication.translate("MainWindow", u"Spray", None))
        self.actionFill.setText(QCoreApplication.translate("MainWindow", u"Fill", None))
        self.actionTest.setText(QCoreApplication.translate("MainWindow", u"Test", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionSepia.setText(QCoreApplication.translate("MainWindow", u"Sepia", None))
        self.actionPixelate.setText(QCoreApplication.translate("MainWindow", u"Pixelate", None))
        self.actionBlur_2.setText(QCoreApplication.translate("MainWindow", u"Simple Blur", None))
        self.actionAntialias.setText(QCoreApplication.translate("MainWindow", u"Antialias", None))
        self.actionMelt.setText(QCoreApplication.translate("MainWindow", u"Melt", None))
        self.actionMosaic.setText(QCoreApplication.translate("MainWindow", u"Mosaic", None))
        self.actionShear.setText(QCoreApplication.translate("MainWindow", u"Shear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuImage.setTitle(QCoreApplication.translate("MainWindow", u"Image", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuFilters.setTitle(QCoreApplication.translate("MainWindow", u"Filters", None))
        self.menuBlur.setTitle(QCoreApplication.translate("MainWindow", u"Blur", None))
#if QT_CONFIG(statustip)
        self.statusbar.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.toolButtonChecker_11.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonPen.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonDropper.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonWand.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonSelectionLasso.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonZoomOut.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonRoundRectangle.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(accessibility)
        self.toolButtonSelectionCircle.setAccessibleName(QCoreApplication.translate("MainWindow", u"\u00c7ember", None))
#endif // QT_CONFIG(accessibility)
        self.toolButtonSelectionCircle.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonCrop.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonChecker.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonRectangle.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonSpray.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonFlipHorizontal.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonChecker_14.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonMirror.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonPan.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonCircle.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonGradient.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonText.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonZoomIn.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonZoomReset.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonSelectionRectangle.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonLine.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonEraser.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonBrush.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonFill.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonFlipVertical.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButtonCircleOutline.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.dwColorBox.setWindowTitle(QCoreApplication.translate("MainWindow", u"Colors", None))
        self.dockWidgetLayers.setWindowTitle(QCoreApplication.translate("MainWindow", u"Layers", None))
        ___qtreewidgetitem = self.treeWidget.headerItem()
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("MainWindow", u"Locked", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("MainWindow", u"Layer", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"Visible", None));

        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        ___qtreewidgetitem1 = self.treeWidget.topLevelItem(0)
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("MainWindow", u"Background", None));
        self.treeWidget.setSortingEnabled(__sortingEnabled)

        self.toolButton_2.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_6.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_3.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_7.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_5.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_4.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_width.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.label_softness.setText(QCoreApplication.translate("MainWindow", u"Softness", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Opacity", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Tolerance", None))
        self.label_2_radius.setText(QCoreApplication.translate("MainWindow", u"Radius", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Density", None))
    # retranslateUi

